"use client";

import { BaseMap } from "@/components/BaseMap";
import { StaticRegionsMap } from "@/components/StaticRegionsMap";
import { useRef } from "react";
import { MapProvider, MapRef } from "react-map-gl";

export default function Page() {
  return (
    <article className="tridentAgentArticle">
      <section className="tridentAgentSection">
        <h2>2023年9月 モロッコ地震 レポート</h2>
        <h4>generated by: `TRIDENT Agent (Sep 18 version)`</h4>
        <p>Note: `TRIDENT Agent` may produce inaccurate information.</p>
      </section>
      <section className="tridentAgentSection">
        <div className="tridentAgentSectionTitle">
          <h3>災害の概要</h3>
        </div>
        <div className="tridentAgentSectionMain">
          <ul>
            <li>
              2023年9月8日22時11分（UTC）、モロッコでマグニチュード6.8の強力な地震が発生しました
            </li>
            <li>
              9月8日の国家当局の情報によると、死者は２９４６人、負傷者は５６７４人に達したとのことです。
            </li>
            <li>
              モロッコ政府は緊急対応を実施しており、さらに国連は各国当局と緊密なコミュニケーションを続けています。
            </li>
          </ul>
        </div>
      </section>
      <section className="tridentAgentSection">
        <div className="tridentAgentSectionTitle">
          <h3>モロッコの概要</h3>
        </div>
        <div className="tridentAgentSectionMain">
          <ul>
            <li>
              政治体制:
              モロッコは立憲君主制で、国王が元首であり、議会制民主主義国です。
            </li>
            <li>
              主要言語:
              アラビア語とベルベル語が公用語であり、フランス語も広く使用されています。
            </li>
            <li>人口: 約3,690万人（2021年推定）</li>
            <li>
              民族構成:
              アラブ・ベルベル系が主要で、他にもさまざまな民族が存在します。
            </li>
            <li>主要通貨: モロッコ・ディルハム（MAD）</li>
            <li>
              経済規模: 世界銀行によると、2020年のGDPは約1,240億米ドルです。
            </li>
            <li>
              主要産業:
              農業、観光業、製造業、鉱業が主要な産業セクターです。特に、リゾート地への観光が重要な経済活動の一部です。
            </li>
            <li>
              医療水準:
              モロッコは国内外の医療施設を提供し、一般的な医療サービスが利用可能ですが、質とアクセスには地域差があります。
            </li>
            <li>
              教育水準:
              教育制度が整備されており、基本的な教育が提供されていますが、地域差があります。フランス語が教育の一部として重要です。
            </li>
          </ul>
        </div>
      </section>
      <section className="tridentAgentSection">
        <div className="tridentAgentSectionTitle">
          <h3>モロッコの位置</h3>
        </div>
        <div className="tridentAgentSectionMain">
          <StaticRegionsMap
            mapStyle="/map_styles/fiord-color-gl-style/style.json"
            regionNames={["Morocco"]}
            mapPadding={400}
          />
        </div>
        <div className="tridentAgentSectionDescription">
          <h4>
            モロッコは北アフリカに位置する国で、地中海に面し、アフリカ大陸の最北端に位置しています。
          </h4>
        </div>
      </section>
      <section className="tridentAgentSection">
        <div className="tridentAgentSectionTitle">
          <h3>モロッコの地形</h3>
        </div>
        <div className="tridentAgentSectionMain">
          <StaticRegionsMap
            mapStyle="/map_styles/arcgis-world-imagery/style.json"
            regionNames={["Morocco"]}
          />
        </div>
        <div className="tridentAgentSectionDescription">
          <h4>
            モロッコは多様な地形を持ち、山岳地帯、砂漠、平原、海岸線があります。最も有名な地形はアトラス山脈です。
          </h4>
          <h4>
            モロッコの気候は多様で、地中海性気候、砂漠気候、山岳気候などがあります。
          </h4>
        </div>
      </section>
      <section className="tridentAgentSection">
        <div className="tridentAgentSectionTitle">
          <h3>地震の主な被害地域</h3>
        </div>
        <div className="tridentAgentSectionMain">
          <StaticRegionsMap
            mapStyle="/map_styles/arcgis-world-imagery/style.json"
            regionNames={["Morocco", "Al Haouz Province", "Taroudant province"]}
            mapPadding={-80}
          />
        </div>
        <div className="tridentAgentSectionDescription">
          <h4>被害の中心は、アル・ハウズ州とタルーダント州です。</h4>
        </div>
      </section>
      <section className="tridentAgentSection">
        <div className="tridentAgentSectionTitle">
          <h3>地震被害の詳細</h3>
        </div>
        <div className="tridentAgentSectionDescription">
          <h4>地震被害の詳細は、今後生成される予定です。</h4>
        </div>
      </section>
      <section className="tridentAgentSection">
        <h4>レポートは以上です。</h4>
      </section>
    </article>
  );
}
