services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}
        target: /app
    ports:
      - 3000:3000
    networks:
      - trident

networks:
  trident:
    name: trident

volumes:
  ollama:
  overpass-db:
