"use client";

import { StaticRegionsMap } from "@/components/StaticRegionsMap";

export default function Page() {
  return (
    <>
      <title>
        2023年9月 リビア洪水 レポート - TRIDENT Agent (Sep 18 version)
      </title>
      <article className="tridentAgentArticle">
        <section className="tridentAgentSection">
          <h2>2023年9月 リビア洪水 レポート</h2>
          <h4>generated by: `TRIDENT Agent (Sep 18 version)`</h4>
          <p>Note: `TRIDENT Agent` may produce inaccurate information.</p>
        </section>
        <section className="tridentAgentSection">
          <div className="tridentAgentSectionTitle">
            <h3>災害の概要</h3>
          </div>
          <div className="tridentAgentSectionMain">
            <ul>
              <li>
                9月10日、暴風雨ダニエルがリビアに上陸し、リビア北東部の数カ所に強風や突然の大雨などの悪天候をもたらしました。
              </li>
              <li>
                リビア北東部を襲った洪水と鉄砲水の発生を受け、WHO情報筋によると、9月14日現在、5,000人以上が死亡したと推定され、合計3,922人の死亡が病院に登録されています。
              </li>
              <li>
                依然として1万人以上が行方不明となっており、入手可能なデータが限られていることから、この数字は過小評価されている可能性が高いです。
              </li>
            </ul>
          </div>
        </section>
        <section className="tridentAgentSection">
          <div className="tridentAgentSectionTitle">
            <h3>リビアの概要</h3>
          </div>
          <div className="tridentAgentSectionMain">
            <ul>
              <li>
                政治体制:
                リビアは政治的に不安定で、様々な派閥や勢力が存在します。2011年のリビア内戦以降、国内の政治情勢は不安定が続いています。
              </li>
              <li>主要言語: アラビア語が公用語として話されています。</li>
              <li>人口: 約703万人（2021年推定）</li>
              <li>
                民族構成:
                リビアの主要な民族はアラブ人で、またベルベル人やトゥアレグ人などの少数民族も存在します。
              </li>
              <li>主要通貨: リビア・ディナール（Libyan Dinar）</li>
              <li>
                経済規模:
                リビアの経済は主に石油産業に依存しており、石油輸出が主要な収入源です。ただし、政治的不安定さにより経済に不確定要因が存在します。
              </li>
              <li>
                主要産業:
                主要産業は石油およびエネルギー関連産業、農業（主にオアシス地域で行われます）、鉱業です。
              </li>
              <li>
                医療水準:
                リビアの医療体制は政治的不安定さや資金不足のために影響を受けており、一部の地域では医療水準が低い状態が続いています。
              </li>
              <li>
                教育水準:
                リビアには教育制度が存在し、基本的な教育は提供されていますが、政治的混乱により教育水準にも影響が及んでいます。
              </li>
            </ul>
          </div>
        </section>
        <section className="tridentAgentSection">
          <div className="tridentAgentSectionTitle">
            <h3>リビアの位置</h3>
          </div>
          <div className="tridentAgentSectionMain">
            <StaticRegionsMap
              mapStyle="/map_styles/fiord-color-gl-style/style.json"
              regionNames={["Libya"]}
              mapPadding={400}
            />
          </div>
          <div className="tridentAgentSectionDescription">
            <h4>リビアは北アフリカに位置する国で、地中海に面しています。</h4>
          </div>
        </section>
        <section className="tridentAgentSection">
          <div className="tridentAgentSectionTitle">
            <h3>リビアの地形</h3>
          </div>
          <div className="tridentAgentSectionMain">
            <StaticRegionsMap
              mapStyle="/map_styles/arcgis-world-imagery/style.json"
              regionNames={["Libya"]}
            />
          </div>
          <div className="tridentAgentSectionDescription">
            <h4>
              主に砂漠が広がり、サハラ砂漠が国内の大部分を占めています。北部には地中海に面した海岸線があります。
            </h4>
            <h4>
              リビアは乾燥した砂漠気候が広がり、夏は非常に暑く、冬は比較的穏やかです。内陸部では気温が極端に上昇することもあります。
            </h4>
          </div>
        </section>
        <section className="tridentAgentSection">
          <div className="tridentAgentSectionTitle">
            <h3>災害の主な被害地域</h3>
          </div>
          <div className="tridentAgentSectionMain">
            <StaticRegionsMap
              mapStyle="/map_styles/fiord-color-gl-style/style.json"
              regionNames={["Libya", "Derna District"]}
              mapPadding={180}
            />
          </div>
          <div className="tridentAgentSectionDescription">
            <h4>被害の中心は、デルナ県です。</h4>
          </div>
        </section>
        <section className="tridentAgentSection">
          <div className="tridentAgentSectionTitle">
            <h3>災害による建物被害の詳細</h3>
          </div>
          <div className="tridentAgentSectionMain">
            <StaticRegionsMap
              mapStyle={{
                version: 8,
                sources: {
                  worldImagery: {
                    type: "raster",
                    tiles: [
                      "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                    ],
                    tileSize: 256,
                    attribution:
                      '<a href="https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/" target="_blank">Source: Esri, Maxar, Earthstar Geographics</a>',
                  },
                  buildingDamageAssessment: {
                    type: "geojson",
                    data: "https://shi-works.github.io/Satellite-Image-Map-of-Lybia-Flooding/EMSR696_AOI01_GRA_PRODUCT_builtUpP_v1.geojson",
                    cluster: false,
                    attribution:
                      '<a href="https://rapidmapping.emergency.copernicus.eu/EMSR695/download">© Copernicus Emergency Management Service, Earthquake in Marrakesh-Safi Region, Morocco</a>',
                  },
                },
                layers: [
                  {
                    id: "worldImagery",
                    type: "raster",
                    source: "worldImagery",
                    minzoom: 0,
                    maxzoom: 22,
                  },
                  {
                    id: "building-damage-assessment",
                    type: "circle",
                    source: "buildingDamageAssessment",
                    minzoom: 0,
                    maxzoom: 22,
                    paint: {
                      "circle-color": [
                        "match",
                        ["get", "damage_gra"],
                        "Damaged",
                        "rgba(255, 255, 0, 1)",
                        "Destroyed",
                        "rgba(255, 0, 0, 1)",
                        "Possibly damaged",
                        "rgba(0, 255, 0, 1)",
                        "rgba(0, 0, 0, 1)",
                      ],
                      "circle-radius": 6,
                      "circle-stroke-width": 1,
                      "circle-stroke-color": "rgba(0, 0, 0, 1)",
                    },
                  },
                ],
              }}
              regionNames={["Derna District"]}
              mapPadding={150}
            />
            <div
              style={{
                position: "absolute",
                left: 0,
                bottom: "8em",
                backgroundColor: "white",
                paddingBottom: "5px",
              }}
            >
              <h4>建物被害評価</h4>
              <div
                style={{
                  backgroundColor: "rgb(255, 0, 0)",
                  border: "1px solid black",
                  display: "inline-block",
                  marginLeft: "5px",
                }}
              >
                <span style={{ display: "inline-block", padding: "4px" }}>
                  倒壊
                </span>
              </div>
              <div
                style={{
                  backgroundColor: "rgb(255, 255, 0)",
                  border: "1px solid black",
                  display: "inline-block",
                  marginLeft: "5px",
                }}
              >
                <span style={{ display: "inline-block", padding: "4px" }}>
                  損傷あり
                </span>
              </div>
              <div
                style={{
                  backgroundColor: "rgb(0, 255, 0)",
                  border: "1px solid black",
                  display: "inline-block",
                  marginLeft: "5px",
                  marginRight: "5px",
                }}
              >
                <span style={{ display: "inline-block", padding: "4px" }}>
                  おそらく損傷あり
                </span>
              </div>
            </div>
            <div className="tridentAgentSectionDescription">
              <h4>災害被害の詳細は、今後更新される予定です。</h4>
            </div>
          </div>
        </section>
        <section className="tridentAgentSection">
          <h4>レポートは以上です。</h4>
          <h4>
            <a
              href="https://tasks.hotosm.org/organisations/osm-libya"
              target="_blank"
            >
              OpenStreetMapを通じて災害対応を支援することができます
            </a>
          </h4>
          {window && (
            <h4>
              <a
                href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(
                  "2023年9月 リビア洪水 レポート - TRIDENT Agent (Sep 18 version)\n"
                )}&url=${encodeURIComponent(window.location.href)}`}
                target="_blank"
              >
                このレポートをXへ投稿する
              </a>
            </h4>
          )}
        </section>
      </article>
    </>
  );
}
