export const placeholders = [
  "What is the United Nations in a nutshell?",
  "What is the primary role of the United Nations?",
  "What was the reason for the formation of the UN?",
  "When and where was the United Nations Charter signed?",
  "Where is the headquarters of the UN?",
  "How can the UN use artificial intelligence to achieve our goal?",
  "Concisely describe the UN's concern on artificial intelligence.",
  "How much the UN place a high priority on GIS?",
  "Give me several examples of the UN peacekeeping missions.",
  "Which region is the UN most concerned about poverty?",
  "Which region is the UN most concerned about sanitation issues?",
  "Which region is the UN most concerned about human rights issues?",
  "Which region is the UN most concerned about climate change?",
  "Does the UN take gender into account in its climate change action?",
  "Why is the UN taking gender considerations into account in climate change action?",
  "What is the name of the UN mission in South Sudan?",
  "When did the UN start mission in South Sudan?",
  "What is the UNMISS?",
  "Why did the UN start UNMISS?",
  "Who is the latest head of South Sudan at the UN mission?",
  "Where is the headquarters of the UN mission in South Sudan?",
  "Where is the headquarters of the UNIFIL?",
  "Where is the headquarters of UNHCR?",
  "Where is the headquarters of WHO?",
  "Where is the headquarters of the World Bank?",
  "Where is the Permanent Mission of Japan to the United Nations?",
];
