export const incidents: {
  name: string;
  nameJa: string;
  relatedIncidents: string[];
  relatedIncidentsJa: string[];
}[] = [
  {
    name: "Protection",
    nameJa: "保護",
    relatedIncidents: [
      "Conflicts",
      "Terrorism",
      "Mass displacement",
      "GBV",
      "Child rights violations",
      "Mines/ERW",
      "Forced evictions",
      "HLP disputes",
    ],
    relatedIncidentsJa: [
      "紛争",
      "テロ",
      "大規模移動・避難",
      "性暴力",
      "子どもの権利侵害",
      "地雷・不発弾",
      "強制立ち退き",
      "住居・土地・財産問題",
    ],
  },
  {
    name: "CCCM",
    nameJa: "キャンプ管理",
    relatedIncidents: [
      "Mass displacement",
      "IDP camp establishment",
      "Conflicts",
      "Sudden-onset disasters",
    ],
    relatedIncidentsJa: [
      "大規模避難",
      "国内避難民キャンプ設置",
      "紛争",
      "突発災害",
    ],
  },
  {
    name: "Shelter",
    nameJa: "シェルター",
    relatedIncidents: [
      "Earthquakes",
      "Floods",
      "Cyclones/Typhoons",
      "Urban fires",
      "Conflicts",
      "Winter emergencies",
    ],
    relatedIncidentsJa: [
      "地震",
      "洪水",
      "サイクロン／台風",
      "都市火災",
      "紛争",
      "冬季危機",
    ],
  },
  {
    name: "Education",
    nameJa: "教育",
    relatedIncidents: [
      "School closures in emergencies",
      "Conflicts",
      "Natural disasters",
      "Displacement",
      "Attacks on education",
    ],
    relatedIncidentsJa: [
      "緊急時の学校閉鎖",
      "紛争",
      "自然災害",
      "避難・移動",
      "教育への攻撃",
    ],
  },
  {
    name: "Food Security",
    nameJa: "食料安全保障",
    relatedIncidents: [
      "Drought",
      "Floods",
      "Conflicts",
      "Economic shocks",
      "Market disruptions",
      "Locust infestations",
      "Famine risk",
    ],
    relatedIncidentsJa: [
      "干ばつ",
      "洪水",
      "紛争",
      "経済ショック",
      "市場機能不全",
      "サバクトビバッタ被害",
      "飢饉リスク",
    ],
  },
  {
    name: "Health",
    nameJa: "保健",
    relatedIncidents: [
      "Disease outbreaks",
      "Pandemics",
      "Mass casualty events",
      "Conflicts",
      "Natural disasters",
      "Health system collapse",
    ],
    relatedIncidentsJa: [
      "感染症の流行",
      "パンデミック",
      "多数傷病者事案",
      "紛争",
      "自然災害",
      "保健医療体制の崩壊",
    ],
  },
  {
    name: "Nutrition",
    nameJa: "栄養",
    relatedIncidents: [
      "Famine/IPC Phase 5",
      "Acute malnutrition",
      "Drought",
      "Food price spikes",
      "Disease outbreaks",
    ],
    relatedIncidentsJa: [
      "飢饉（IPC5）",
      "急性栄養不良",
      "干ばつ",
      "食料価格高騰",
      "感染症流行",
    ],
  },
  {
    name: "WASH",
    nameJa: "水・衛生（WASH）",
    relatedIncidents: [
      "Cholera and waterborne diseases",
      "Floods",
      "Drought/Water scarcity",
      "Displacement settlements",
      "Damage to water systems",
    ],
    relatedIncidentsJa: [
      "コレラ等の水系感染症",
      "洪水",
      "干ばつ・水不足",
      "避難・仮設居住地",
      "給水・下水インフラ被害",
    ],
  },
  {
    name: "Logistics",
    nameJa: "物流",
    relatedIncidents: [
      "Access constraints",
      "Damaged infrastructure",
      "Air/sea/land corridor disruptions",
      "Import restrictions",
      "Insecurity",
    ],
    relatedIncidentsJa: [
      "アクセス制約",
      "インフラ損壊",
      "空路・海路・陸路の寸断",
      "輸入規制",
      "治安悪化",
    ],
  },
  {
    name: "Emergency Telecommunications",
    nameJa: "緊急通信",
    relatedIncidents: [
      "Communications outages",
      "Power failures",
      "Natural disasters",
      "Conflicts",
      "Coordination ICT needs",
    ],
    relatedIncidentsJa: [
      "通信途絶",
      "停電",
      "自然災害",
      "紛争",
      "調整用ICT需要",
    ],
  },
  {
    name: "Early Recovery",
    nameJa: "早期回復",
    relatedIncidents: [
      "Post-disaster recovery",
      "Post-conflict recovery",
      "Debris management",
      "Livelihoods restoration",
      "Governance and essential services",
    ],
    relatedIncidentsJa: [
      "災害後復旧",
      "紛争後復旧",
      "瓦礫撤去",
      "生計回復",
      "統治・基礎サービス再建",
    ],
  },
];
